#!/bin/bash
#
# create-kvm-vm
#
# Install virtaul machine in KVM
#
# (C) 2017 Stefan Schallenberg

##### Main ###################################################################
# Parameters und Options see kvm-create-vm in kvm-functions.sh
# This file is DEPRECATED

. $(dirname "$BASH_SOURCE")/kvm-functions.sh || exit 1

kvm_create-vm "$@"
exit $?

