# localVolume-template.yaml
#
# create localVolume
#
# (C) 2021-2024 Stefan Schallenberg

# jscpd:ignore-start

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${share}.${KUBE_APP}.${KUBE_STAGE}
  labels:
    state: "${KUBE_STAGE}"
    app: "${KUBE_APP}"
    share: "${share}"
spec:
  storageClassName: "nafets"
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  volumeMode: ${volmode}
###   storageClassName: local-storage
  local:
    path: ${path}
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: ${key}
              operator: In
              values:
                - ${value}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${share}.${KUBE_APP}
  namespace: ${KUBE_NAMESPACE}
  labels:
    app: "${KUBE_APP}"
    share: "${share}"
spec:
  storageClassName: "nafets"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeMode: ${volmode}
  selector:
    matchLabels:
      state: "${KUBE_STAGE}"
      app: "${KUBE_APP}"
      share: "${share}"

# jscpd:ignore-end
